# Docs at https://github.com/mxabierto/adela/wiki/Docker#docker-compose
postgres:
  image: postgres
  volumes:
    - <ADELA-POSTGRES-VOLUME-PATH>:/var/lib/postgresql
  ports:
    - "5432"
redis:
  image: redis
  ports:
    - "6379"
sidekiq:
  build: .
  command: bundle exec sidekiq
  links:
    - postgres
    - redis
web:
  build: .
  environment:
    - SECRET_KEY_BASE=<SECRET-KEY-BASE>
  ports:
    - "80:80"
  links:
    - postgres
    - redis
